thickness_default: &thickness_default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: thickness
  password: Vms.1946!
  host: mysql.varland.com

timeclock_default: &timeclock_default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails_timeclock
  password: Vms.1946!
  host: mysql.varland.com

development:
  thickness:
    <<: *thickness_default
    database: thickness_dev
  timeclock:
    <<: *timeclock_default
    database: timeclock_dev
  
test:
  thickness:
    <<: *thickness_default
    database: thickness_test
  timeclock:
    <<: *timeclock_default
    database: timeclock_test
  
production:
  thickness:
    <<: *thickness_default
    database: thickness
  timeclock:
    <<: *timeclock_default
    database: timeclock_rails